In [13]:
import numpy as np
#int8
a8=np.array([-100,0,100,200,300],dtype=np.int8)
#uint8
u8=np.array([-100,0,100,200,300],dtype=np.uint8)
#int32
a32=np.array([-1,0,1,2,3,4,5],dtype=np.int32)
#int32
u32=np.array([-1,0,1,2,3,4,5],dtype=np.uint32)
print(a8)
print(u8)
print(a32)
print(u32)


[-100    0  100  -56   44]
[156   0 100 200  44]
[-1  0  1  2  3  4  5]
[4294967295          0          1          2          3          4
          5]


C:\Users\ileum\AppData\Local\Temp\ipykernel_53532\526055872.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a8=np.array([-100,0,100,200,300],dtype=np.int8)
C:\Users\ileum\AppData\Local\Temp\ipykernel_53532\526055872.py:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a8=np.array([-100,0,100,200,300],dtype=np.int8)
C:\Users\ileum\AppData\Local\Temp\ipykernel_53532\526055872.py:5: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -100 to uint8 will

In [31]:
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])